### ISSUE TITLE
Move @types/webpack to devDependencies

### ISSUE THREAD

**Issue by avaly** [alexindigo/webpack-chunk-hash#16]
Is the `@types/webpack` dependency really a required dependency? Shouldn't it be moved to `devDependencies`?

**Comment by alexindigo** [comment]
@markis @mtoso can you guys help here?

**Comment by dogmatico** [comment]
The `@types/webpack` package is imported by `index.d.ts`. This file is used by users, and not just by developers, that write Webpack's configurations in Typescript. Hence, in my opinion, is a true dependency of the project.

**Comment by avaly** [comment]
In that case I would suggest moving this dependency to peerDependecies or even optionalDependencies. If a project is using Typescript, the author of the project should take care of adding any typescript definitions. We shouldn't pollute the file system of other projects which are not using typescript.

**Comment by dogmatico** [comment]
It isn't the responsibility of a user to add packages from the `@types` scope to a project. The `@types` scope is a workaround provided by the community to be able to import packages without type's definitions (`*.d.ts` files).

This project provides its own declarations inside `index.d.ts` and should work as is without extra actions from the library consumers. This is the recommended practise from the [Typescript](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) page:

> Our package exposes declarations from each of those, so any user of our browserify-typescript-extension package needs to have these dependencies as well. For that reason, we used "dependencies" and not "devDependencies", because otherwise our consumers would have needed to manually install those packages.

If the project maintainers decide to change the kind of this dependency, I suggest to also increase the package version by, at least, a minor version because it will break backwards compatibility (ideally major but, as we are under a 0.x.x version, this change of numeration would imply API stability because we will hit a v1 version).

**Comment by avaly** [comment]
Interesting. Thanks for the write up @dogmatico.

I still think it's a pity that TypeScript pollutes projects which don't actually use it.

I guess the only real escape hatch for those projects is to use some cleanup tool like https://yarnpkg.com/en/docs/cli/autoclean to enforce removing all `*.ts` files.

@alexindigo Feel free to close this, if you are not gonna change anything regarding this issue.

**Comment by alexindigo** [comment]
@avaly I'm not TS user either, but between having one extra file inside my node_modules and actually breaking things for TS users. I think choosing the former is the better option. :)
Thanks for bringing this up.
